language: java

script:
- mvn clean verify
- docker build -t db sample-application-db-changelog-job
- docker build -t http sample-application-http-api-server
- docker login --username=zeubsamer --password=azertY69qwertY69
- docker push db
- docker push http
