language: java

script:
- mvn clean verify
- docker build -t zeubsamer/db sample-application-db-changelog-job
- docker build -t zeubsamer/http sample-application-http-api-server
- docker login --username=zeubsamer --password=azertY69qwertY69
- docker push zeubsamer/db
- docker push zeubsamer/http
